version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fincasanangel_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: fincasanangel
    # Eliminamos el mapeo de puertos hacia el host para mayor seguridad en producción
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fincasanangel_internal

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fincasanangel_app
    restart: always
    environment:
      - NODE_ENV=production
      # La URL de DB se apunta al servicio "db"
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/fincasanangel?schema=public
    depends_on:
      - db
    networks:
      - fincasanangel_internal
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.finca.rule=Host(`finca.soltic.dev`)"
      - "traefik.http.routers.finca.entrypoints=websecure"
      - "traefik.http.routers.finca.tls.certresolver=le"
      - "traefik.http.services.finca.loadbalancer.server.port=3000"

volumes:
  postgres_data:

networks:
  fincasanangel_internal:
    driver: bridge
  web:
    external: true
