version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fincasanangel_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: fincasanangel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fincasanangel_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # La URL de DB se apunta al servicio "db"
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/fincasanangel?schema=public
    depends_on:
      - db
    # Volumen montado para hot-reload
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:
